### ISSUE TITLE
Convert integration tests to use docker

### ISSUE THREAD

**Issue by shoekstra** [dev-sec/chef-os-hardening#180]
Hi @artem-sidorenko @chris-rock ,

Any objection to creating a PR that updates the travis job to use chefdk and docker images instead of DO instances?  Would be good to get feedback in PRs w/o needing to fork it somewhere and would get quicker response if using docker.

But perhaps there was a reason to use DO so thought to ask here before creating PR.

Cheers,

**Comment by artem-sidorenko** [comment]
@shoekstra thanks for raising this question! The problem is, you can't test everything of this cookbook within containers: you need a real system. This is due to the lots of system changes, which you can't really do within a container, e.g. sysctl flags or similar things. Possible and acceptable way would be to split the things and to test a subset within container always and other options with real VMs on the master runs only. See https://github.com/dev-sec/chef-os-hardening/issues/142 for some discussion about that in the past

**Comment by shoekstra** [comment]
That sounds reasonable.  My main reason for asking was for the ability to run tests as contributor without relying on someone to fork and manually run the tests.

Perhaps you could include the DO tokens in the run as [travis encrypted variables](https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables) sometime in the future?

I'll close this for now, thanks for the prompt response!

**Comment by artem-sidorenko** [comment]
@shoekstra yes, I know :-(

> Perhaps you could include the DO tokens in the run as travis encrypted variables sometime in the future?

This would not help here. The encrypted vars are available only for the base repo, but not the forks. In the current setup you can add your DO token to your fork configuration in the travis. Via this you will get running CI for your fork. (but PRs are again a bit different here due to travis, as you have two CI runs in the PR)
